[workspace]
members = [
  "archive-http",
  "cli",
  "core",
  "mailpot-tests",
  "rest-http",
  "web",
]

[profile.release]
lto = "fat"
opt-level = "z"
codegen-units = 1
split-debuginfo = "unpacked"
