[workspace]
resolver = "2"

members = [
  "mailpot",
  "mailpot-archives",
  "mailpot-cli",
  "mailpot-http",
  "mailpot-tests",
  "mailpot-web",
]

[profile.release]
lto = "fat"
opt-level = "z"
codegen-units = 1
split-debuginfo = "unpacked"
