[package]
name = "mailpot-cli"
version = "0.1.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
edition = "2018"
license = "LICENSE"
readme = "README.md"
description = "mailing list manager"
repository = "https://github.com/meli/mailpot"
keywords = ["mail", "mailing-lists" ]
categories = ["email"]
default-run = "mpot"

[[bin]]
name = "mpot"
path = "src/main.rs"

[dependencies]
mailpot = { version = "0.1.0", path = "../core" }
structopt = "0.3.16"
stderrlog = "^0.5"
log = "0.4"
