[package]
name = "mpot-archives"
version = "0.1.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
edition = "2018"
license = "LICENSE"
readme = "README.md"
description = "mailing list manager"
repository = "https://github.com/meli/mailpot"
keywords = ["mail", "mailing-lists" ]
categories = ["email"]
default-run = "mpot-archives"

[[bin]]
name = "mpot-archives"
path = "src/main.rs"

[dependencies]
mailpot = { version = "0.1.0", path = "../core" }
tokio = { version = "1", features = ["full"] }
askama = "0.8"
warp = "0.3"
percent-encoding = "2.1"
